version: '3'
services:
  varnish:
    image: varnish:6.5
    ports:
      - 80:80
    volumes:
      - './docker/varnish/etc/varnish.vcl:/etc/varnish/default.vcl'

  php:
    build:
      context: ./docker/php/
    volumes:
      - './src:/var/www/html'
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM
      - PHP_IDE_CONFIG=serverName=localhost

  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    build:
      context: ./docker/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/volume/mysql:/var/lib/mysql
