version: '3'
services:
  php:
    image: php:7.4-fpm

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root