version: '3'
services:
  php:
    build:
      context: ./docker/php/
    image: php:7.4-fpm
    container_name: php
    volumes:
      - './src:/var/www/html'
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - php

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
#    volumes:
#      - '.'
